blog/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns('',
                       url(r'^$', views.PostListView.as_view(), name="list"),
                       url(r'^(?P<slug>[\w-]+)$', views.PostDetailView.as_view(), name="detail"),
                       )

mblog/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin

from . import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.HomepageView.as_view(), name='home_page'),
    url(r'^blog/', include('blog.urls', namespace='blog')),  # notice the quotes needed around blog.urls
    url(r'^admin/', include(admin.site.urls)),
)

if not settings.DEBUG:  # Needed in order to get Heroku to find CSS. I don't understand why this is needed.
    urlpatterns += patterns('',
                            (r'^static/(.*)$', 'django.views.static.serve', {
                                'document_root': settings.STATIC_ROOT
                            }),
    )

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


class PostManager(models.Manager):  # see https://docs.djangoproject.com/en/1.5/topics/db/managers/
    def live(self):
        return self.model.objects.filter(published=True)


class Post(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False, null=True, blank=True)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True, default='')
    content = models.TextField()
    published = models.BooleanField(default=True)
    author = models.ForeignKey(User, related_name="posts")
    category = models.CharField(max_length=127)
    objects = PostManager()  # this is for the published=True PostManager

    class Meta:
        ordering = ["-created_at", "title"]  # descending order indicated by "-" in front of created_at
    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        override save to add default slug, if no slug is specified
        :param args:
        :param kwargs:
        """
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        '''
        purpose: to replace in template, this: {% url 'blog:detail' post.slug %}
                 with this: {% post.get_absolute_url %}
        This allows database-y type info to be contained to model, and don't need to mess
        with get URL from future when using Django 1.4 and earlier
        '''
        return "blog:detail", (), {"slug": self.slug}

blog/views.py
from django.shortcuts import render, render_to_response
# from django.template import RequestContext # to get my css file to be seen
from django.views.generic import ListView, DetailView
from .models import Post


class PublishedPostsMixin(object):
    def get_queryset(self):
        return self.model.objects.live()  # this is much less readable then before
        # queryset = super(PublishedPostsMixin, self).get_queryset()
        # return queryset.filter(published=True)
        # this is what we had before the ModelManager change


class PostListView(PublishedPostsMixin, ListView):
    model = Post

    # def get_queryset(self):
    #     queryset = super(PostListView, self).get_queryset()
    #     return queryset.filter(published=True)


class PostDetailView(PublishedPostsMixin, DetailView):
    model = Post

# noticed how the pk is no longer passed in. And then can change pk to some other identifier like slug
# and it still works . . . seems magical . . .



# def blog_list(request, *args, **kwargs):
#     post_list = Post.objects.filter(published=True)
#     template_name = "post_list.html"
#     context = {
#         "post_list": post_list
#     }
#
#     return render(request, template_name, context)

# def blog_detail(request, pk, *args, **kwargs):
#     post = Post.objects.get(pk=pk, published=True)
#     template_name = "post_detail.html"
#     context = {
#         "post": post
#     }
#
#     return render(request, template_name, context)

mblog/views.py
from django.views.generic import TemplateView


class HomepageView(TemplateView):
    template_name = "homepage.html"


# def home_page(request):
#     return render_to_response('homepage.html', context_instance=RequestContext(request))

blog/templates/blog/post_detail.html
{% extends "_layouts/base.html" %}

{% block page_title %}{{ post.title }}{% endblock %}

{% block page_content %}
  <h2>{{ post.title }}</h2>

{{ post.content|linebreaks }}
  <p>{{ post.updated_at }}</p>
  <p><a href="{% url 'blog:list' %}">&larr; Blog list</a></p>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "_layouts/base.html" %}

{% block page_title %}Blog posts | {% endblock %}

{% block page_content %}
  <h2>Blog Posts</h2>

  <ul>
    {% for post in post_list %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
      {% empty %}
      <li>Sorry, no posts yet. Check back soon!</li>
    {% endfor %}
  </ul>
{% endblock %}

mblog/templates/_layouts/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block page_title %}{% endblock %}Microblog</title>
  <link type="text/css" href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet"/>
  <link type="text/css" href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" rel="stylesheet"/>
</head>
<body>
<div class="container">
  <h1>Welcome to my site!</h1>
  {% block page_content %}{% endblock %}
</div>
</body>
</html>

mblog/templates/homepage.html
{% extends "_layouts/base.html" %}

{% block page_content %}
  <div class="row-fluid" xmlns="http://www.w3.org/1999/html">
  <h2>Hello There!</h2>

  <p>This is a blog. A microblog, actually.</p>

  <p>It's all about learning, with <a href="http://gettingstartedwithdjango.com/">Getting Started with Django</a></p>

  <a href="{% url 'blog:list' %}" class="btn">Read my blog</a>
  </div>
{% endblock %}